spring.application.name=iExpense
# Database connection URL (default port is 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/Expense_Manager

# Database username
spring.datasource.username=postgres

# Database password
spring.datasource.password=postgres

# Optional: Hibernate properties if using Spring Data JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true